### ISSUE TITLE
Odd crash when running muse_bias

### ISSUE THREAD

**Issue by jbrinchmann** [olebole/python-cpl#25]
Hi Ole, I am trying to run the latest DRS on some MUSE GTO data and for most data it works fine but I am now getting repeatedly the same odd error - I am not sure what the most essential part is so I am attaching the log, but it might be around the bit just below:

I did see previous related issues mentioning /tmp. I have modest amounts of space in /tmp but it should be sufficient and it works for all other calibration sets so I doubt this is the issue

(base) [jarle@muse1 logs]$ df -kh /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda4        50G  9.1G   38G  20% /

```17:39:54 [  DEBUG][CplThread] cpl.muse_bias.muse_utils_frameset_merge_frames: Removing "MASTER_BIAS-01.fits" ("MASTER_BIAS" vs "MASTER_BIAS").
17:40:08 [  ERROR][MainThread] cpl.muse_bias: Recipe crashed. Traceback (most recent call last):
17:40:08 [  ERROR][MainThread] cpl.muse_bias.slot_tp_call:   File "/tmp/build/80754af9/python_1544812943833/work/Objects/typeobject.c", line 6376, in slot_tp_call

17:40:08 [  ERROR][MainThread] cpl.muse_bias.slot_tp_call:   Local variables:
17:40:08 [  ERROR][MainThread] cpl.muse_bias.slot_tp_call:     PyId___call__ = {next = 0x561016abe5c0 <PyId___instancecheck__.13499>, string = 0x5610169de5e1 "__call__", object = 0x7f8e6824a170}
17:40:08 [  ERROR][MainThread] cpl.muse_bias.slot_tp_call:     unbound = 1
17:40:08 [  ERROR][MainThread] cpl.muse_bias.slot_tp_call:     res = <optimized out>
17:40:08 [  ERROR][MainThread] cpl.muse_bias._PyObject_Call_Prepend:   File "/tmp/build/80754af9/python_1544812943833/work/Objects/call.c", line 904, in _PyObject_Call_Prepend
```
[muse_bias-2019-05-01T17:38:34.327152.log](https://github.com/olebole/python-cpl/files/3135227/muse_bias-2019-05-01T17.38.34.327152.log)

**Comment by olebole** [comment]
That sounds weird. Especially the last lines of the log, which show the function where this happens:
```
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:   File "/home/jarle/Source/MUSE-DRS/v2.6/muse-kit-2.6/cfitsio/getkey.c", line 2814, in ffgphd

17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:   Parameters:
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     fptr = 0x561017b17720
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     maxdim = <optimized out>
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     simple = <optimized out>
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     bitpix = <optimized out>
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     naxis = <optimized out>
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     naxes = <optimized out>
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     pcount = 0x7ffd6950a798
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     gcount = 0x7ffd6950a7a0
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     extend = 0x7ffd6950a790
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     bscale = 0x7ffd6950a7b0
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     bzero = 0x7ffd6950a7b8
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     blank = 0x7ffd6950a7a8
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     nspace = 0x7ffd6950a794
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     status = 0x7ffd6950ffb4
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:   Local variables:
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     unknown = 0
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     found_end = 0
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     tstatus = 0
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     ii = <optimized out>
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     nextkey = 283
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     namelen = 20
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     longbitpix = 16
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     longnaxis = 2
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     axislen = 0
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     message = "0\250Pi\375\177\000\000\200\247Pi\375\177\000\000SIMPLE  =", ' ' <repeats 20 times>, "T / Standard FITS (NOST-100-2.0)\000   "
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     keyword = "NAXIS2\000\000\\\245Pi\375\177\000\000GROUPS\000\000\005\000\000\000\034\004\000\000\002\000\000\000\006\000\000\000|\245Pi\375\177\000\000GROUPS\000\000\377\377\377\377\034\004\000\000\002\000\000\000\006\000\000"
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     card = "HIERARCH ESO INS AO FOCU1 DEC = -441858.40000 / Telescope desclination [deg].\000  "
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     name = "ESO INS AO FOCU1 DEC\000\000G\000\000\000N\000\000ON\000\000S\000\000RCTG\000\000\000\000\000\000\000\000SIMPLE\000\000\000ERSION\000\000S\000\000RCTG"
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     value = "T\000\000i\003\000\000\000@\332Pi\375\177\000\000\270\377Pi\375\177\000\000\220\336U\027\020V\000\000\226\245Pi\375\177\000\000\207d\235>\216\177\000\000\000\000\000\000\000\000\000\000\200\247Pi\375\177\000\000`\023\364\026\020V"
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     comm = "FITS Extension may be present\000\000\000\260\246Pi\375\177\000\000\060\246Pi\375\177\000\000\020\250Pi\375\177\000\000T\312Pi\375\177\000\000\300=\002\000\000\000\000\000\025"
17:40:08 [  ERROR][MainThread] cpl.muse_bias.ffgphd:     xtension = "\220\245Pi\375\177\000\000\006\000\000\000\006\000\000\000\064\245Pi\375\177\000\000\006\000\000\000\000\000\000\000\221\245Pi\375\177\000\000\005\000\000\000\001\000\000\000@\245Pi\375\177\000\000<\245Pi\375\177\000\000\261\245Pi\375\177"
17:40:08 [  ERROR][MainThread] cpl.muse_bias: SIGHUP: Hangup
```
This is cfitsio; however I have no idea what could cause the `SIGHUP`. `SIGHUP` is usually not caused by the program itself, but by some other program (f.e. a shell that sends this to its children when `stdin`, `stdout` or `stderr` are disconnected).
Other that guessing something like this, I have no idea.
Is this reproducible?

**Comment by jbrinchmann** [comment]
I have removed everything and restarted the reduction and now it runs through this, so I suspect a corrupted file somewhere. (I now have a problem with the twilight recipe which causes a segmentation fault but I'll dig a bit for that). So it seems to not be reproducible. I'll close it.
